apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-svc-active
spec:
  selector:
    app: guestbook-ui
  type:  ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-svc-preview
spec:
  selector:
    app: guestbook-ui
  type:  ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
